version: 2.1

defaults: &defaults
  docker:
    - image: atotto/debian-builder:latest
  working_directory: /workspace
  environment:
    GOPATH: /
    GOCACHE: /.cache/go-build

jobs:
  build:
    <<: *defaults
    steps:
    - run: go env
    - checkout
    - restore_cache:
        keys:
        - go-module-cache-v1-{{ checksum "/workspace/go.sum" }}
        - go-module-cache-v1-
    - run: go mod download
    - save_cache:
        key: go-module-cache-v1-{{ checksum "/workspace/go.sum" }}
        paths:
        - /pkg/mod/cache
    - run: go test -v ./...
    - run: go build 
    - run: go-bin-deb generate --arch amd64
    - persist_to_workspace:
        root: /workspace
        paths:
        - "*.deb"

  deploy:
    <<: *defaults
    steps:
    - attach_workspace:
        at: /workspace
    - run: packagecloud push atotto/debian-utils/any/any packagecloud_*.deb || true

workflows:
  version: 2
  test:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master
